export const INPUT_VALUE_UPDATED = 'INPUT_VALUE_UPDATED';
export const INITIALIZE_FIELDS = 'INITIALIZE_FIELDS';
export const SUBMITTED_USER_INFO = 'SUBMITTED_USER_INFO';
export const TABLE_HEADERS_CHANGED = 'TABLE_HEADERS_CHANGED';