export const INPUT_VALUE_CHANGE_STARTED = 'INPUT_VALUE_CHANGE_STARTED';
export const INPUT_VALUE_CHANGE_SUCCESS = 'INPUT_VALUE_CHANGE_SUCCESS';
export const INPUT_VALUE_CHANGE_FAILED = 'INPUT_VALUE_CHANGE_FAILED';